/* Generated by tools/gen_launcher_icons.py — do not edit by hand.
 *
 * Launcher glyphs taken from Lucide (lucide-static v1.50.0, ISC):
 * 24x24 grid, 2px stroke, round caps/joins. Emitted as 8-bit-alpha LVGL
 * v9 images (LV_COLOR_FORMAT_A8, one byte per pixel) rendered at 4x and
 * LANCZOS-downscaled, so curves keep a grayscale antialias ramp.
 *
 * They carry no colour: the launcher tints them through
 * lv_obj_set_style_img_recolor_*, which is how the focused tile's icon
 * turns accent-coloured without a second copy of the art.
 */
#ifndef UI_LAUNCHER_ICONS_H
#define UI_LAUNCHER_ICONS_H

#include "lvgl.h"

extern const lv_image_dsc_t ui_icon_music;
extern const lv_image_dsc_t ui_icon_ebook;
extern const lv_image_dsc_t ui_icon_gear;
extern const lv_image_dsc_t ui_icon_bt;

#endif /* UI_LAUNCHER_ICONS_H */
