/*
 * Launcher (home screen). Replaces the old text list menu.
 *
 * A 3×2 grid of icon tiles; only the first four slots are populated for now
 * (music / ebook / settings / bluetooth — the 5th and 6th stay empty). The
 * grid is walked with the arrow keys: up/down change rows, left/right change
 * columns, and the nearest valid slot in the requested direction wins. Enter
 * opens the selected page.
 *
 * Page-local state lives here; the assembly layer (ui.c) only calls build /
 * refresh / nav / enter through ui_internal.h.
 */
#include <stdio.h>
#include <string.h>

#include "lvgl.h"
#include "ui.h"
#include "ui_internal.h"
#include "ui_launcher_icons.h"
#include "ui_strings.h"
#include "ui_theme.h"
#include "ui_widgets.h"

/* Which slots are live. Empty slots (indices 4 and 5) are simply not created,
 * so the grid reads as four icons in a 3-column frame. */
typedef enum {
    ICON_MUSIC = 0,
    ICON_EBOOK,
    ICON_GEAR,
    ICON_BT,
} launch_icon_t;

typedef struct {
    int           row;
    int           col;
    launch_icon_t icon;
    const char   *name;
    ui_page_t     page;
} launch_slot_t;

static const launch_slot_t s_launch[] = {
    {0, 0, ICON_MUSIC, "音乐",   UI_PAGE_PLAYER},
    {0, 1, ICON_EBOOK, "电子书", UI_PAGE_EBOOK_LIST},
    {0, 2, ICON_GEAR,  "设置",   UI_PAGE_SETTINGS},
    {1, 0, ICON_BT,    "蓝牙",   UI_PAGE_BT},
};
#define LAUNCH_COUNT ((int)(sizeof(s_launch) / sizeof(s_launch[0])))

static int s_launch_sel = 0;

static ui_tiles_t s_tiles;
static lv_obj_t  *s_icon_img[UI_TILE_COUNT];   /* per-slot glyph, kept for focus tinting */

/* ---- Icons ----------------------------------------------------------------
 * The four glyphs are 8-bit-alpha bitmaps generated by
 * tools/gen_launcher_icons.py: drawn at 4x and downscaled with LANCZOS, so the
 * curves keep a grayscale antialias ramp rather than hard 1bpp steps. They
 * carry no colour of their own — the launcher tints them via img_recolor,
 * which is what turns the focused tile's icon accent-coloured. ---- */

static const void *launch_icon_src(launch_icon_t icon)
{
    switch (icon) {
    case ICON_MUSIC: return &ui_icon_music;
    case ICON_EBOOK: return &ui_icon_ebook;
    case ICON_GEAR:  return &ui_icon_gear;
    case ICON_BT:    return &ui_icon_bt;
    }
    return &ui_icon_music;   /* unreachable; silences -Wreturn-type */
}

void ui_build_launcher(void)
{
    lv_obj_t *mp = lv_obj_create(s_ui.screen);
    lv_obj_remove_style_all(mp);
    lv_obj_set_pos(mp, 0, 0);
    lv_obj_set_size(mp, UI_SCREEN_W, UI_SCREEN_H);
    lv_obj_set_style_bg_color(mp, ui_theme_color(UI_COLOR_BG), 0);
    lv_obj_set_style_bg_opa(mp, LV_OPA_COVER, 0);
    lv_obj_clear_flag(mp, LV_OBJ_FLAG_SCROLLABLE);
    s_ui.menu_page = mp;

    /* Title bar. */
    lv_obj_t *title = lv_label_create(mp);
    lv_label_set_text(title, "小喵掌机");
    lv_obj_set_pos(title, UI_TITLE_X, UI_TITLE_Y);
    lv_obj_set_style_text_font(title, UI_FONT, 0);
    lv_obj_set_style_text_color(title, ui_theme_color(UI_COLOR_TITLE), 0);
    ui_theme_separator(mp, UI_SEP_Y);

    /* Tiles at their grid positions (only the live slots). */
    int xs[UI_TILE_COUNT], ys[UI_TILE_COUNT];
    for (int i = 0; i < LAUNCH_COUNT; i++) {
        xs[i] = UI_TILE_X(s_launch[i].col);
        ys[i] = UI_TILE_Y(s_launch[i].row);
    }
    ui_tiles_create(&s_tiles, mp, LAUNCH_COUNT, xs, ys, UI_TILE_W, UI_TILE_H);

    for (int i = 0; i < LAUNCH_COUNT; i++) {
        lv_obj_t *bg = s_tiles.tile[i].bg;
        ui_theme_text_set(s_tiles.tile[i].label, s_launch[i].name);

        lv_obj_t *img = lv_img_create(bg);
        lv_img_set_src(img, launch_icon_src(s_launch[i].icon));
        lv_obj_set_size(img, UI_TILE_ICON, UI_TILE_ICON);
        /* LV_ALIGN_TOP_MID hands the centring to LVGL instead of computing
         * (UI_TILE_W - UI_TILE_ICON) / 2 by hand: the glyph then stays put
         * whatever the tile width, border or bitmap edge becomes. The
         * vertical offset centres it in the space above the caption. */
        lv_obj_align(img, LV_ALIGN_TOP_MID, 0,
                     (UI_TILE_LABEL_Y - UI_TILE_ICON) / 2);
        /* Tint dim up front: an A8 bitmap renders white until recoloured, and
         * ui_refresh_launcher() only overrides the focused slot. */
        lv_obj_set_style_img_recolor_opa(img, LV_OPA_COVER, 0);
        lv_obj_set_style_img_recolor(img, ui_theme_color(UI_COLOR_TEXT_DIM), 0);
        s_icon_img[i] = img;
    }

    /* Bottom band: position indicator left, key legend right. */
    s_ui.menu_status = ui_theme_label_at(mp, "", 4, UI_LEGEND_Y, 120,
                                         UI_COLOR_TEXT_DIM, LV_TEXT_ALIGN_LEFT);
    s_ui.hint = ui_theme_label_at(mp, "A:进入  ←→选  ↑↓换排", 130, UI_LEGEND_Y, 186,
                                  UI_COLOR_TEXT_DIM, LV_TEXT_ALIGN_RIGHT);
}

void ui_refresh_launcher(void)
{
    ui_tiles_set_focus(&s_tiles, LAUNCH_COUNT, s_launch_sel);

    /* Tint the glyphs to match the tile focus: accent on the selected slot,
     * dim on the rest. Recolouring the one bitmap (rather than swapping
     * sources) keeps the unselected icons from competing with the focus. */
    for (int i = 0; i < LAUNCH_COUNT; i++) {
        lv_obj_set_style_img_recolor(s_icon_img[i],
                                     ui_theme_color(i == s_launch_sel
                                                    ? UI_COLOR_ACCENT
                                                    : UI_COLOR_TEXT_DIM), 0);
    }

    char buf[32];
    snprintf(buf, sizeof(buf), "[%d/%d]", s_launch_sel + 1, LAUNCH_COUNT);
    ui_theme_text_set(s_ui.menu_status, buf);
}

/* Arrow-key navigation over the grid. Left/right walk the row-major slot order
 * and wrap around at the ends, so pressing left on the first slot (or right on
 * the last) carries onto the other row instead of sticking at the grid edge.
 * Up/down step between rows, preferring the slot nearest the current column. */
void ui_launcher_nav(uint32_t key)
{
    const int cur = s_launch_sel;

    if (key == LV_KEY_LEFT || key == LV_KEY_RIGHT) {
        /* s_launch is stored in row-major order, so stepping the index moves
         * horizontally and rolls over to the next/previous row at the ends. */
        const int step = (key == LV_KEY_RIGHT) ? 1 : LAUNCH_COUNT - 1;
        s_launch_sel = (cur + step) % LAUNCH_COUNT;
        ui_refresh_launcher();
        return;
    }
    if (key != LV_KEY_UP && key != LV_KEY_DOWN) {
        return;
    }

    const int row = s_launch[cur].row;
    const int col = s_launch[cur].col;
    const int tr  = (key == LV_KEY_UP) ? row - 1 : row + 1;

    int best = cur, best_dist = 1000;
    for (int i = 0; i < LAUNCH_COUNT; i++) {
        if (i == cur) {
            continue;
        }
        if (s_launch[i].row != tr) {
            continue;
        }
        const int dc = abs(s_launch[i].col - col);   /* prefer same column */
        if (dc < best_dist) {
            best_dist = dc;
            best = i;
        }
    }
    s_launch_sel = best;
    ui_refresh_launcher();
}

/* Page of the current selection — what ENTER opens. */
ui_page_t ui_launcher_page(void)
{
    return s_launch[s_launch_sel].page;
}

void ui_launcher_reset(void)
{
    s_launch_sel = 0;
}
